---
- hosts: all
  gather_facts: no
  
  tasks:
  - name: Copy script to node
    win_copy:
      src: "{{ playbook_dir }}/files/get_recyclebin.ps1"
      dest: C:\ansible_temp\

  - name: Run script
    win_command: C:\ansible_temp\get_recyclebin.ps1
    register: recycle_size

  - name: Clear recycle bin
    win_command: Clear-RecycleBin -Force
    when: recycle_size >= "{{ size_threshold }}"