---
- hosts: all
  gather_facts: no
  
  tasks:
  - name: Run script
    win_shell: >
      Get-ChildItem C:\Windows\Temp -Recurse |
      Select-Object Length | 
      Measure-Object -Property Length -Sum | 
      Select-Object -expand Sum
    register: result

  - name: Set value
    set_fact:
     temp_size: "{{ result.stdout | int }}"

  - name: Clear windows temp
    win_shell: >
      Get-ChildItem C:\Windows\Temp -Recurse | 
      Remove-Item -Force
    when: temp_size | int >= size_threshold