---
- hosts: all
  gather_facts: no
  
  tasks:
  - name: Copy script to node
    win_copy:
      src: "{{ playbook_dir }}/files/get_recyclebin.ps1"
      dest: C:\ansible_temp\

  - name: Run script
    win_command: powershell.exe -File C:\ansible_temp\get_recyclebin.ps1
    register: result

  - name: Set value
    set_fact:
     recycle_size: "{{ result.stdout | int }}"

  - name: Clear recycle bin
    win_command: powershell.exe Clear-RecycleBin -Force
    when: recycle_size | int >= size_threshold