- name: Install Datadog Agent on servers in AWS
  hosts: all
  become: yes
  vars:
    datadog_api_key: "{{ dd_api_key }}"
    datadog_site: "{{ dd_site }}"
    datadog_config:
      tags:
        - env:dev
      logs_enabled: true
      process_config:
        enabled: "true"

  roles:
    - { role: Datadog.datadog, become: yes }
