---

- name: "Manage event log"
  hosts: all
  gather_facts: no

  tasks:
  - name: Set event log values
    win_eventlog:
      name: "{{ log_name }}"
      maximum_size: "{{ max_size | default(omit)}}"
      overflow_action: "{{ ovf_action | default(omit) }}"
      retention_days: "{{ rtn_days | default(omit) }}"
      state: "{{ state | default(omit) }}"
