---

- name: "Update Windows AMI"
  hosts: all
  gather_facts: no

  tasks:
  - name: "Check disk space used"
    include_role:
      name: show_disk_info

  - name: "Calculate used vs threshold"
    debug:
      var: used_percent

  - name: "Clear logs"
    include_role:
      name: clear_event_logs
    when: ( used_percent > disk_used_threshold ) | bool
  
  - name: "Patch windows"
    include_role:
      name: patch_windows