---

- name: "Update Windows AMI"
  hosts: all
  gather_facts: yes

  tasks:
  - name: "Clear logs"
    include_role:
      name: clear_event_logs
    when: clear_logs | bool
  
  - name: "Patch windows"
    include_role:
      name: patch_windows