---

- name: "Show log info"
  hosts: all
  gather_facts: no

  tasks:
  - name: "Get log facts"
    win_eventlog:
      name: "{{ item }}"
    with_items: "{{ log_list }}"
    register: log_facts

#  - debug:
#      var: log_facts

  - name: Print log info
    debug:
      msg:
        - "Log Name: {{ item.name }}"
        - "Overflow Action: {{ item.overflow_action }}"
        - "Log Entries: {{ item.entries }}"
        - "Retention Days: {{ item.retention_days }}"
        - "Max Size (KB): {{ item.maximum_size_kb }}"
    with_items: "{{ log_facts.results }}"