---

- name: "Show disk info"
  hosts: all
  gather_facts: no

  tasks:
  - name: "Get disk facts"
    win_disk_facts:

  - name: "Show disk size"
    debug:
      msg: "system disk size: {{ disksize_gib_human }}"
    vars:
      disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
      disksize_gib_human: '{{ disk.size|filesizeformat(true) }}'
 