---

- name: "Show disk info"
  hosts: all
  gather_facts: no

  tasks:
  - name: "Get disk facts"
    win_disk_facts:

#  - name: "Wait for connection on all hosts."
#    wait_for:
#      host: "{{ item['tagged_instances'][0]['private_ip'] }}"
#      port: 5986
#      timeout: 300
#    loop: "{{ ec2.results }}"
#    loop_control:
#      label: "{{ item['tagged_instances'][0]['private_ip'] }}"  