---
- name: print count
  debug:
    msg: "found_update_count: {{ found_update_count }}"

- name: print scan results
  debug:
    msg: "Updates needed:{{ found_updates }}"
  when: found_update_count | int >= 1
