---
- name: "Get disk facts"
  win_disk_facts:

- name: "Show disk size"
  debug:
    msg: "system disk size: {{ disksize_gib_human }}"
  vars:
    disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
    disksize_gib_human: '{{ disk.size|filesizeformat(true) }}'

- name: "Show size remaining"
  debug:  
    msg: "size remaining: {{ size_remaining }}"
  vars:
    disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
    size_remaining: '{{ disk.partitions[0].volumes[0].size_remaining|filesizeformat(true) }}'

- name: "Show disk info"
  debug:
    msg: 
      - "system disk size: {{ disk_size | filesizeformat(true) }}"
      - "size remaining: {{ size_remaining | filesizeformat(true)}}"
      - "disk used percentage: {{ used_percent | float | round(1, 'floor')}}%"
  vars:
    disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
    disk_size: '{{ disk.size }}'
    size_remaining: '{{ disk.partitions[0].volumes[0].size_remaining }}'
    used_percent: '{{ size_remaining | float / disk_size | float }}'    