---
- name: Install Windows Updates
  win_updates:
    category_names: "{{ categories | default(omit) }}"
    state: installed
    log_path: c:\ansible_win_updates.txt
    reboot: "{{ reboot_server }}"
  register: update_result
