---
- name: Install Windows Updates
  win_updates:
    category_names: "{{ categories | default(omit) }}"
    whitelist: "{{ kb_list | default(omit) }}"
    state: "{{ update_state }}"
    log_path: c:\ansible_win_updates.txt
    reboot: "{{ reboot_server }}"
  register: update_result
