---
- name: Download the Apache installer
  win_get_url:
    url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
    dest: C:\windows\temp\

- name: Install MSI
  win_package: 
    path: C:\windows\temp\httpd-2.2.25-win32-x86-no_ssl.msi
    state: present
  when: software_state == 'install'

- name: Remove MSI
  win_package: 
    path: C:\windows\temp\httpd-2.2.25-win32-x86-no_ssl.msi
    state: absent
  when: software_state == 'remove'